### ISSUE TITLE
Use case 1: Create a VDB

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-datavirt#61]
see https://docs.google.com/document/d/1N_2YpFdnoRhMInmESEHk01TtCGm9hfursM0MPLQwVSs/edit#bookmark=id.d9goxmxbmbt0

related steps:

- [x] Provide a "Create VDB" command
- [x] Provide DDL auto-generated when creating a new VDB file #60
- [x] Provided VDB name needs to follow OpenShift resource name convention #59 
- [x] Provide full naming for VDB in "DataVirt: Create VDB" command name #29 
- [x] Open "vdb" file after creation #30
- [x] Provide tests to cover creation of VDB file #45

bug:

- [ ] dirty editor doesn't warn about data loss when being closed #102

**Comment by lhein** [comment]
functionality in place. writing the tests is next.

**Comment by lhein** [comment]
Please create a FUSETOOLS2 issue for this.

**Comment by lhein** [comment]
https://issues.redhat.com/browse/FUSETOOLS2-370
